version: "2"

run:
  timeout: 5m
  issues-exit-code: 2
  tests: false

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

exclude:
  - Using the variable on range scope `tt` in function literal

exclude-rules:
  - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
    linters: [ govet ]

exclude-dirs:
  - mocks
